In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# Get dimension
a = np.array([1,2,3])
a.ndim

# Get shape
a.shape

# Get Type
a.dtype

# Get size
a.itemsize

# Get the total size
a.nbytes



(3,)

# ndarray object
Numpy is used to work with arrays. The array object in Numpy is called ndarray.

# Dimensions in Arrays.
- This is a one level of array depth(Nested arrays.)
- 0-D arrays or scalars are elements in an array.Each value in an array is a 0-D array.

In [5]:
# # 0-D array

import numpy as np
arr = np.array(45)
print(arr)

45


# 1-D arrays
- This is an array that has 0-D arrays as its elements.It is called a uni-dimensional array.

In [6]:
# 1-d array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# 2-D Arrays
- An array that has 1-D arrays as its elements.
- Used to represent matrix or 2nd order tensors.


In [7]:
import numpy as np
arr = np.array([[1,2,2,3,4,],[4,5,6,7,7]])
print(arr)

[[1 2 2 3 4]
 [4 5 6 7 7]]


# 3- D arrays
- Has 2-D arrays(matrices) as its elements.
- Often used to represent a 3rd order tensor.

In [8]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
# checking dimensions in the array 
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
